baseURL: "/"
languageCode: en-us
title: "altescy"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable Google Analytics
# googleAnalytics: UA-XXXXXXXXX-X

# Enable Disqus forum
disqusShortname: altescy

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # Copyright Notice
  copyright: © 2020 Copyright.

  # Meta description for your site.  This will help the search engines to find your site.
  description: Portfolio and personal blog of altescy.

  # background image of the landing page
  background: "/images/background.jpg"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will be default to the theme logos if not provided.
  logo:
    main: /images/logo_trans.png
    inverted: /images/logo_trans.png
    favicon: /images/logo_trans.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/altescy/altescy.github.io

  # specify whether you want to write blog post or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  # customMenus:
  # - name: Notes
  #   url: https://hossainnotes.netlify.app/docs/example/

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false

  # some information about you
  author:
    name: "Yasuhiro Yamaguchi"
    nickname: "altescy"
    image: "/images/logo.png"
    # greeting message before your name. it will default to "Hi! I am" if not provided
    greeting: "Hi, I'm"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "altescy@fastmail.com"
      # phone: "+0123456789"
    # a summary of what you do
    summary:
    - I am a Master's students in NAIST
    - I am interested in ML and NLP technologies
    - I work with Python and Go
